# -*- coding: utf-8 -*-
"""dcalab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GYJllFI01pMFO2cha9E-Ddz6ZwOMADeF
"""


import simpy
import random

random.seed(25)

def criaChegadas(env, taxa, tec_lab, proporcao,p_coleta_propria):
    contaChegadas = 0
    tipos = list(proporcao.keys())
    pesos = list(proporcao.values())

    while True:
        # espera até a próxima chegada (exponencial)
        yield env.timeout(random.expovariate(1 / taxa))
        contaChegadas += 1

        # escolhe tipo segundo a proporção
        tipo = random.choices(tipos, weights=pesos, k=1)[0]

        # sorteia se é coleta própria
        coleta_propria = random.random() < p_coleta_propria

        # nomeia o pedido (podemos mudar pra input() depois)
        pedido = f"Exame_{contaChegadas}"

        if coleta_propria:
            print(f"{env.now:.1f}: {pedido} Chegou! | ({tipo}, Coleta já realizada pelo PACIENTE)")
            env.process(EntregaAmostra(env, pedido, tipo, tec_lab))
        else:
            print(f"{env.now:.1f}: {pedido} Chegou! | ({tipo}, Coleta no LABORATÓRIO)")
            env.process(ColetaAmostra(env, pedido, tipo, tec_lab))


def ColetaAmostra(env, pedido, tipo, tec_lab):
    # mapa numérico de prioridade (menor = atende antes)
    prioridade = {"Urgente": 0, "Rotina": 1}
    prio = prioridade.get(tipo, 1)

    # solicita o recurso com prioridade
    with tec_lab.request(priority=prio) as req:
        yield req  # aguarda até conseguir o recurso
        print(f"{env.now:.1f}: Coletando {pedido}. | ({tipo}, Prioridade = {prio})")

        # tempo de serviço por tipo (pode vir de um dicionário externo)
        tempos = {"Urgente": 3.0, "Rotina": 5.0}
        t = tempos.get(tipo, 5.0)
        yield env.timeout(t)

        print(f"{env.now:.1f}: {pedido} coletado! | ({tipo}) - durou {t} min")
        env.process(Registro_sistema(env,pedido,tec_lab,tipo))

def EntregaAmostra(env, pedido, tipo, tec_lab):
    print(f"{env.now:.1f}: {pedido} chegou com amostra própria | ({tipo})")
    #Ajustar esse tempo de entrega e quem recebe esse exame
    yield env.timeout(1.5)
    print(f"{env.now:.1f}: {pedido} amostra recebida! | ({tipo})")
    env.process(Registro_sistema(env, pedido, tec_lab,tipo))

def Registro_sistema(env,pedido,tec_lab,tipo):
    with tec_lab.request() as req:
        yield req  # aguarda até conseguir o recurso
        print(f"{env.now:.1f}: Registrando {pedido}.")
        yield env.timeout(2)
        print(f"{env.now:.1f}: {pedido} registrado!")
        env.process(Transporte(env,pedido,tec_lab,tipo))

def Transporte(env,pedido,tec_lab,tipo):
    with tec_lab.request() as req:
        yield req  # aguarda até conseguir o recurso
        print(f"{env.now:.1f}: Transportando {pedido}. ")
        yield env.timeout(2)
        print(f"{env.now:.1f}: {pedido} foi entregue para triagem.")
        env.process(Triagem(env,pedido,tipo,triagista))

def Triagem(env, pedido, tipo, triagista):
    # mapa numérico de prioridade (menor = atende antes)
    prioridade = {"Urgente": 0, "Rotina": 1}
    prio = prioridade.get(tipo, 1)

    # solicita o recurso com prioridade
    with triagista.request(priority=prio) as req:
        yield req  # aguarda até conseguir o recurso
        print(f"{env.now:.1f}: Iniciando triagem do {pedido}. | ({tipo}, Prioridade = {prio})")

        # tempo de serviço por tipo (pode vir de um dicionário externo/alterar depois quando souber tempos corretos)
        tempos = {"Urgente": 2.0, "Rotina": 3.0}
        t = tempos.get(tipo, 3.0)
        yield env.timeout(t)

        print(f"{env.now:.1f}: Triagem do {pedido} finalizada! | ({tipo}) - durou {t} min")
        env.process(Classificacao(env,pedido,func_dis,tipo))

def Classificacao(env,pedido,func_dis,tipo):
    with func_dis.request() as req:
        yield req  # aguarda até conseguir o recurso
        print(f"{env.now:.1f}: Classificando {pedido}.")
        #Alterar tempo depois que passarem esse dado
        yield env.timeout(2)
        print(f"{env.now:.1f}: {pedido} classificado!")
        yield env.process(Desv3(env,pedido,tipo))

def Desv3(env, pedido, tipo):
    tipos = list(proporcao2.keys())
    pesos = list(proporcao2.values())
    resultado = random.choices(tipos, weights=pesos, k=1)[0]

    if resultado == "Adequado":
        print(f"{env.now:.1f}: {pedido} classificado como {resultado} → segue para PROCESSAMENTO.")
        yield env.process(Processamento_tec(env,pedido,func_dis,tipo))
    else:
        print(f"{env.now:.1f}: {pedido} classificado como {resultado} → volta para COLETA.")
        yield env.process(ColetaAmostra(env, pedido, tipo, tec_lab))

def Processamento_tec(env,pedido,func_dis,tipo):
    with func_dis.request() as req:
        yield req  # aguarda até conseguir o recurso
        print(f"{env.now:.1f}: Processando {pedido}.")
        #Alterar tempo depois que passarem esse dado
        yield env.timeout(2)
        print(f"{env.now:.1f}: {pedido} foi processado!")
        env.process(Validacao_tec(env,pedido,tec_lab,tipo))

def Validacao_tec(env,pedido,tec_lab,tipo):
    with tec_lab.request() as req:
        yield req  # aguarda até conseguir o recurso
        print(f"{env.now:.1f}: Validando tecnicamente {pedido}. ")
        #Alterar tempo depois que passarem esse dado
        yield env.timeout(2)
        print(f"{env.now:.1f}: {pedido} foi validado tecnicamente! ")
        env.process(Validacao_clnica(env,pedido,analista,tipo))

def Validacao_clnica(env,pedido,analista,tipo):
    with analista.request() as req:
        yield req  # aguarda até conseguir o recurso
        print(f"{env.now:.1f}: Validando clinicamente {pedido}. ")
        #Alterar tempo depois que passarem esse dado
        yield env.timeout(2)
        print(f"{env.now:.1f}: {pedido} foi validado clinicamente!")
        env.process(Desv4(env,pedido,tipo))

def Desv4(env, pedido, tipo):
    tipos = list(proporcao3.keys())
    pesos = list(proporcao3.values())
    resultado = random.choices(tipos, weights=pesos, k=1)[0]

    if resultado == "Critico":
        print(f"{env.now:.1f}: {pedido} classificado como {resultado} → segue para TELEFONEMA.")
        yield env.process(Telefonema(env,pedido,analista,tipo))
        return #Para evitar cair nos próximos ramos

    elif tipo == "Urgente":
        print(f"{env.now:.1f}: {pedido} classificado como {tipo} → segue para IMPRESSAO.")
        yield env.process(Impressao(env,pedido,func_dis,tipo))
        return
    else:
        print(f"{env.now:.1f}: {pedido} classificado como {resultado} → segue para DISPONIBILIZACAO.")
        yield env.process(Disponibilizacao(env, pedido, tipo))
        return

def Disponibilizacao(env,pedido,tipo):
    print(f"{env.now:.1f}: Disponibilizando o {pedido} ({tipo})")

    # tempo de disponibilização (pode ser fixo ou aleatório e podemos mudar)
    yield env.timeout(1)
    print(f"{env.now:.1f}: {pedido} ({tipo}) foi DISPONIBILIZADO no sistema e saiu do fluxo!")

def Telefonema(env,pedido,analista,tipo):
    with analista.request() as req:
        yield req  # aguarda até conseguir o recurso
        print(f"{env.now:.1f}: Telefonema do {pedido} iniciado")
        #Alterar tempo depois que passarem esse dado
        yield env.timeout(5)
        print(f"{env.now:.1f}: Telefonema do {pedido} finalizado")
        env.process(Disponibilizacao(env,pedido,tipo))

def Impressao(env,pedido,analista,tipo):
    with recepcionista.request() as req:
        yield req  # aguarda até conseguir o recurso
        print(f"{env.now:.1f}: Iniciando impressão do {pedido} ")
        #Alterar tempo depois que passarem esse dado
        yield env.timeout(3)
        print(f"{env.now:.1f}: {pedido} impresso!")
        env.process(Disponibilizacao(env,pedido,tipo))



# ---------- MAIN ----------
env = simpy.Environment()
#proporção de urgentes e rotina (pode ser alterado depois com dados reais)
proporcao = {"Urgente": 0.3, "Rotina": 0.7}
#proporção de adequação (pode ser alterado depois com dados reais)
proporcao2 = {"Adequado": 0.8, "Inadequado":0.2}
#porporção de criticidade
proporcao3 = {"Critico": 0.1, "Nao Critico": 0.9}
# PriorityResource permite requests com prioridade
tec_lab = simpy.PriorityResource(env, capacity=1)  # ajustar capacidade depois conforme número de técnicos
triagista = simpy.PriorityResource(env, capacity=1)  # ajustar capacidade depois conforme número de triagistas
func_dis = simpy.PriorityResource(env, capacity=2)  # ajustar capacidade depois conforme número de funcionarios
analista = simpy.PriorityResource(env, capacity=1)  # ajustar capacidade depois conforme número de analistas
recepcionista = simpy.PriorityResource(env, capacity=1)  # ajustar capacidade depois conforme número de recepcionistas

#considerando 30% que chegam com coleta própria
env.process(criaChegadas(env, taxa=2.0, tec_lab=tec_lab, proporcao=proporcao, p_coleta_propria=0.3))
env.run(until=60)