# -*- coding: utf-8 -*-
"""testedcalab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_2I5LH5gftez_L5ca7jmdmXbmQH8UwCl
"""

import simpy
import random
import pandas as pd

random.seed(25)

#cria uma classe monitor, que irá monitora tempo e emitir relatórios pra cada entidade de exame
class Monitor:
    def __init__(self):
        self.registros = []
        self.tempos_totais = {}
        self.filas = {}

        # Atributos pra computar fila e uso do recurso
        self.tempo_uso_recurso = {}
        self.ocupacao_recurso = {}
        self.fila_tam = {}          # tamanho da fila ao longo do tempo
        self.tempo_espera = {}      # tempos de espera (para média)
        self.tempo_servico = {}     # tempos de atendimento



    def log(self, env, pedido, evento, recurso=None):
        """Registra cada evento relevante"""
        self.registros.append({
            "tempo": env.now,
            "pedido": pedido,
            "evento": evento,
            "recurso": recurso
        })

    def inicio(self, pedido, tempo):
        self.tempos_totais[pedido] = {"inicio": tempo, "fim": None}

    def fim(self, pedido, tempo):
        if pedido in self.tempos_totais:
            self.tempos_totais[pedido]["fim"] = tempo

    def tempo_total(self, pedido):
        t = self.tempos_totais.get(pedido)
        if t and t["fim"] is not None:
            return t["fim"] - t["inicio"]
        return None

      # USOS RECUROS E FILAS
    def registrar_uso_recurso(self, recurso, inicio, fim):
        """Guarda o tempo total de uso de um recurso."""
        duracao = fim - inicio
        if recurso not in self.tempo_uso_recurso:
            self.tempo_uso_recurso[recurso] = 0
        self.tempo_uso_recurso[recurso] += duracao

    def registrar_fila(self, recurso, tamanho, tempo):
        """Registra tamanho da fila em um momento específico."""
        if recurso not in self.fila_tam:
            self.fila_tam[recurso] = []
        self.fila_tam[recurso].append((tempo, tamanho))

    def registrar_tempo_espera(self, recurso, tempo_espera):
        """Registra tempo em fila de um exame."""
        if recurso not in self.tempo_espera:
            self.tempo_espera[recurso] = []
        self.tempo_espera[recurso].append(tempo_espera)

    def registrar_tempo_servico(self, recurso, tempo_servico):
        """Registra tempo de atendimento de um exame."""
        if recurso not in self.tempo_servico:
            self.tempo_servico[recurso] = []
        self.tempo_servico[recurso].append(tempo_servico)



#adicionar tempo em fila, qntd=tidades em fila, qntd recursos em atendimento...



# ==== PARAMS DE TEMPO (em segundos) ====
TEMPOS = {

    "transporte_lab_leito": random.triangular(1.815, 27.510, 6.000), #colocar max(300, random.gauss(xxxx))  # tempo em (exemplo — ajuste conforme necessário)
    "coleta": {"Urgente": random.lognormvariate(0.179, 1.618), "Rotina": random.lognormvariate(0.179, 1.618)},  # intervalo
    "entrega": max(0.3,random.gauss(1.915, 1.857)),                                    # intervalo
    "transporte": random.lognormvariate(-5.733, 36.901),    # valor fixo (média)
    #"triagem": {"Urgente": max(0.15, random.gauss(0.263, 0.152)), "Rotina": max(0.15, random.gauss(0.251, 0.106))},   # intervalo
    "triagem": random.gauss(0.263, 0.152), #max(0.15, random.gauss(0.263, 0.152)),
    #"classificacao": 0.5,                                  # 30 segundos
    "processamento_tec_total": random.betavariate(3.511, 37.100),
    "processamento_tec_total": random.uniform(3,167),
    #random.gauss(29365.714, 13538.139),  # já inclui “validação técnica”
    #"validacao_clin_total": random.betavariate(0.757, 19.928),     # já inclui “investigação”
    #"validacao_clin_total": max(0.5, 125 * random.betavariate(0.757, 19.928)),
    "validacao_clin_total":random.uniform(0,30),
    "telefonema": random.expovariate(0.443) ,
    "disponibilizacao": 1,
    "nomeacao_potes": random.uniform(2, 5),  # intervalo em minutos (ajuste conforme o real)

}

def tempo(nome, tipo=None):
    #Retorna um tempo (min) conforme TEMPOS.
       #- Se for tupla (a,b): sorteia uniforme entre a e b.
       #- Se for dict por tipo: usa chave 'Urgente'/'Rotina'.
       #- Se for número: devolve fixo.

    val = TEMPOS[nome]
    if isinstance(val, dict):
        val2 = val[tipo]
        if isinstance(val2, tuple):
            return random.uniform(*val2)
        return float(val2)
    if isinstance(val, tuple):
        return random.uniform(*val)
    return float(val)

def criaChegadas(env, taxa, tec_lab, proporcao,p_coleta_externa,monitor):
    contaChegadas = 0
    tipos = list(proporcao.keys())
    pesos = list(proporcao.values())

    while True:
        # espera até a próxima chegada (exponencial)
        #yield env.timeout(random.expovariate(1 / taxa))
        yield env.timeout(taxa)
        contaChegadas += 1

        # escolhe tipo segundo a proporção
        tipo = random.choices(tipos, weights=pesos, k=1)[0]

        # sorteia se é coleta própria
        coleta_externa = random.random() < p_coleta_externa

        # nomeia o pedido (podemos mudar pra input() depois)
        pedido = f"Exame_{contaChegadas}"

        #Registra chegada
        monitor.inicio(pedido,env.now)
        monitor.log(env,pedido,"Chegada")


        if coleta_externa:
            print(f"{env.now:.1f}: {pedido} Chegou! | ({tipo}, Coleta já realizada pelo PACIENTE)")
            env.process(EntregaAmostra(env, pedido, tipo, triagista,monitor))
        else:
            print(f"{env.now:.1f}: {pedido} Chegou! | ({tipo}, Coleta no LABORATÓRIO)")
            env.process(NomeacaoPotes(env, pedido, tipo, tec_lab,monitor))

def NomeacaoPotes(env, pedido, tipo, tec_lab, monitor):
    monitor.log(env, pedido, "Inicio nomeação de potes", "tec_lab")

    with tec_lab.request() as req:
        t_entrada_fila = env.now
        fila_atual = len(tec_lab.queue)
        monitor.registrar_fila("tec_lab", fila_atual, env.now)

        yield req  # aguarda o recurso
        tempo_espera = env.now - t_entrada_fila
        monitor.registrar_tempo_espera("tec_lab", tempo_espera)

        inicio_servico = env.now
        monitor.log(env, pedido, "Tec_lab iniciou nomeação de potes", "tec_lab")
        print(f"{env.now:.1f}: Nomeando potes para {pedido}. | ({tipo})")

        duracao_servico = tempo("nomeacao_potes")
        yield env.timeout(duracao_servico)
        fim_servico = env.now

        monitor.registrar_tempo_servico("tec_lab", duracao_servico)
        monitor.registrar_uso_recurso("tec_lab", inicio_servico, fim_servico)

        monitor.log(env, pedido, "Tec_lab finalizou nomeação de potes", "tec_lab")
        print(f"{env.now:.1f}: Nomeação de potes finalizada para {pedido}. | ({tipo})")

        env.process(TransporteLabParaLeito(env, pedido, tipo, tec_lab, monitor))


def TransporteLabParaLeito(env, pedido, tipo, tec_lab, monitor):
    monitor.log(env, pedido, "Inicio deslocamento para leito", "tec_lab")

    with tec_lab.request() as req:
        t_entrada_fila = env.now
        fila_atual = len(tec_lab.queue)
        monitor.registrar_fila("tec_lab", fila_atual, env.now)

        yield req
        tempo_espera = env.now - t_entrada_fila
        monitor.registrar_tempo_espera("tec_lab", tempo_espera)

        inicio_servico = env.now
        monitor.log(env, pedido, "Tec_lab iniciou deslocamento para leito", "tec_lab")
        print(f"{env.now:.1f}: Transportando técnico que irá colher o {pedido} do LABORATÓRIO para o LEITO. | ({tipo})")

        duracao_servico = tempo("transporte_lab_leito")
        yield env.timeout(duracao_servico)
        fim_servico = env.now

        monitor.registrar_tempo_servico("tec_lab", duracao_servico)
        monitor.registrar_uso_recurso("tec_lab", inicio_servico, fim_servico)

        monitor.log(env, pedido, "Tec_lab finalizou deslocamento para leito", "tec_lab")
        print(f"{env.now:.1f}: Transporte concluído — técnico que irá colher o {pedido} chegou ao leito. | ({tipo})")

        env.process(ColetaAmostra(env, pedido, tipo, tec_lab, monitor))


def ColetaAmostra(env, pedido, tipo, tec_lab,monitor):
    monitor.log(env,pedido,"Inicio coleta","tec_lab")
    # mapa numérico de prioridade (menor = atende antes)
    prioridade = {"Urgente": 0, "Rotina": 1}
    prio = prioridade.get(tipo, 1)

    # solicita o recurso com prioridade
    with tec_lab.request(priority=prio) as req:

        #REGISTRO/MONITORAMENTO DE FILAS
        t_entrada_fila = env.now
        fila_atual = len(tec_lab.queue)
        monitor.registrar_fila("tec_lab", fila_atual, env.now)

        yield req  # aguarda até conseguir o recurso

        #tempo de espera
        tempo_espera = env.now - t_entrada_fila
        monitor.registrar_tempo_espera("tec_lab", tempo_espera)

        inicio_servico = env.now
        monitor.log(env,pedido,"Tec_lab iniciou coleta","tec_lab")
        print(f"{env.now:.1f}: Coletando {pedido}. | ({tipo}, Prioridade = {prio})")

        t = tempo("coleta", tipo)
        yield env.timeout(t)

        fim_servico = env.now #registra final do serviço

        monitor.registrar_tempo_servico("tec_lab", t)
        monitor.registrar_uso_recurso("tec_lab", inicio_servico, fim_servico)

        monitor.log(env,pedido,"Tec_lab finalizou coleta","tec_lab")
        print(f"{env.now:.1f}: {pedido} coletado! | ({tipo}) - durou {t} min")

        env.process(Transporte(env,pedido,tec_lab,tipo,monitor))


def EntregaAmostra(env, pedido, tipo, triagista, monitor):
    """
    Entrega de amostras coletadas pelo próprio paciente.
    O triagista confere e recebe o material.
    """
    monitor.log(env, pedido, "Início entrega", "triagista")

    with triagista.request() as req:
        # registra entrada na fila
        t_entrada_fila = env.now
        fila_atual = len(triagista.queue)
        monitor.registrar_fila("triagista", fila_atual, env.now)

        # espera disponibilidade
        yield req
        tempo_espera = env.now - t_entrada_fila
        monitor.registrar_tempo_espera("triagista", tempo_espera)

        # início do serviço
        inicio_servico = env.now
        monitor.log(env, pedido, "Triagista iniciou recebimento amostra própria", "triagista")
        print(f"{env.now:.1f}: Recebendo amostra própria de {pedido}. | ({tipo})")

        duracao_servico = tempo("entrega")
        yield env.timeout(duracao_servico)
        fim_servico = env.now

        # registra tempo e uso do recurso
        monitor.registrar_tempo_servico("triagista", duracao_servico)
        monitor.registrar_uso_recurso("triagista", inicio_servico, fim_servico)

        monitor.log(env, pedido, "Triagista finalizou recebimento amostra própria", "triagista")
        print(f"{env.now:.1f}: {pedido} — amostra recebida! | ({tipo})")


        env.process(Processamento_tec(env, pedido, tec_lab2, tipo, monitor))

def Transporte(env, pedido, tec_lab, tipo, monitor):
    """
    Transporte da amostra até o laboratório.
    Realizado pelo técnico de laboratório.
    """
    monitor.log(env, pedido, "Início transporte", "tec_lab")

    with tec_lab.request() as req:
        # registra entrada na fila
        t_entrada_fila = env.now
        fila_atual = len(tec_lab.queue)
        monitor.registrar_fila("tec_lab", fila_atual, env.now)

        # aguarda disponibilidade do técnico
        yield req
        tempo_espera = env.now - t_entrada_fila
        monitor.registrar_tempo_espera("tec_lab", tempo_espera)

        # início do serviço
        inicio_servico = env.now
        monitor.log(env, pedido, "Tec_lab iniciou transporte pro laboratório", "tec_lab")
        print(f"{env.now:.1f}: Transportando {pedido} do leito até o laboratório. | ({tipo})")

        duracao_servico = tempo("transporte")
        yield env.timeout(duracao_servico)
        fim_servico = env.now

        # registra tempos e uso do recurso
        monitor.registrar_tempo_servico("tec_lab", duracao_servico)
        monitor.registrar_uso_recurso("tec_lab", inicio_servico, fim_servico)

        monitor.log(env, pedido, "Tec_lab finalizou transporte pro laboratório", "tec_lab")
        print(f"{env.now:.1f}: Transporte concluído — {pedido} chegou ao laboratório. | ({tipo})")

        env.process(Triagem(env, pedido, tipo, triagista, monitor))

def Triagem(env, pedido, tipo, triagista, monitor):

    monitor.log(env, pedido, "Início triagem", "triagista")

    with triagista.request() as req:
        # entrada na fila
        t_entrada_fila = env.now
        fila_atual = len(triagista.queue)
        monitor.registrar_fila("triagista", fila_atual, env.now)

        # aguarda disponibilidade
        yield req
        tempo_espera = env.now - t_entrada_fila
        monitor.registrar_tempo_espera("triagista", tempo_espera)

        # início do serviço
        inicio_servico = env.now
        monitor.log(env, pedido, "Triagista iniciou triagem", "triagista")
        print(f"{env.now:.1f}: Iniciando triagem de {pedido}. | ({tipo})")

        duracao_servico = tempo("triagem", tipo)
        yield env.timeout(duracao_servico)
        fim_servico = env.now

        # registra duração e uso
        monitor.registrar_tempo_servico("triagista", duracao_servico)
        monitor.registrar_uso_recurso("triagista", inicio_servico, fim_servico)

        monitor.log(env, pedido, "Triagista finalizou triagem", "triagista")
        print(f"{env.now:.1f}: Triagem de {pedido} finalizada. | ({tipo}) - durou {duracao_servico} min")

        env.process(Desv3(env, pedido, tipo, tec_lab, tec_lab2, monitor))

def Desv3(env, pedido, tipo,tec_lab,tec_lab2,monitor):
    tipos = list(proporcao2.keys())
    pesos = list(proporcao2.values())
    resultado = random.choices(tipos, weights=pesos, k=1)[0]

    if resultado == "Adequado":
        print(f"{env.now:.1f}: {pedido} classificado como {resultado} → segue para PROCESSAMENTO.")
        yield env.process(Processamento_tec(env,pedido,tec_lab2,tipo,monitor))
    else:
        print(f"{env.now:.1f}: {pedido} classificado como {resultado} → volta para COLETA.")
        yield env.process(NomeacaoPotes(env, pedido, tipo, tec_lab,monitor))

def Processamento_tec(env, pedido, tec_lab2, tipo, monitor):
    """
    Etapa de processamento técnico das amostras no laboratório.
    O técnico (tec_lab2) realiza o processamento completo antes da validação.
    """
    monitor.log(env, pedido, "Início processamento", "tec_lab2")

    with tec_lab2.request() as req:
      # registra entrada na fila
      t_entrada_fila = env.now
      fila_atual = len(tec_lab2.queue)
      monitor.registrar_fila("tec_lab2", fila_atual, env.now)

      # aguarda disponibilidade do técnico
      yield req
      tempo_espera = env.now - t_entrada_fila
      monitor.registrar_tempo_espera("tec_lab2", tempo_espera)

      # início do serviço
      inicio_servico = env.now
      monitor.log(env, pedido, "Tec_lab2 iniciou processamento", "tec_lab2")
      print(f"{env.now:.1f}: Iniciando processamento técnico de {pedido}. | ({tipo})")

      duracao_servico = tempo("processamento_tec_total")
      yield env.timeout(duracao_servico)
      fim_servico = env.now

      # registra tempos e uso do recurso
      monitor.registrar_tempo_servico("tec_lab2", duracao_servico)
      monitor.registrar_uso_recurso("tec_lab2", inicio_servico, fim_servico)

      monitor.log(env, pedido, "Tec_lab2 finalizou processamento", "tec_lab2")
      print(f"{env.now:.1f}: Processamento técnico de {pedido} finalizado! | ({tipo})")


      env.process(Validacao_clinica(env, pedido, analista, tipo, monitor))


def Validacao_clinica(env, pedido, analista, tipo, monitor):
    """
    Validação clínica realizada pelo analista após o processamento técnico.
    Verifica resultados e autoriza liberação.
    """
    monitor.log(env, pedido, "Início validação clínica", "analista")

    with analista.request() as req:
        # registra entrada na fila
        t_entrada_fila = env.now
        fila_atual = len(analista.queue)
        monitor.registrar_fila("analista", fila_atual, env.now)

        # aguarda disponibilidade do analista
        yield req
        tempo_espera = env.now - t_entrada_fila
        monitor.registrar_tempo_espera("analista", tempo_espera)

        # início do serviço
        inicio_servico = env.now
        monitor.log(env, pedido, "Analista iniciou validação clínica", "analista")
        print(f"{env.now:.1f}: Iniciando validação clínica de {pedido}. | ({tipo})")

        duracao_servico = tempo("validacao_clin_total")
        yield env.timeout(duracao_servico)
        fim_servico = env.now

        # registra tempos e uso do recurso
        monitor.registrar_tempo_servico("analista", duracao_servico)
        monitor.registrar_uso_recurso("analista", inicio_servico, fim_servico)

        monitor.log(env, pedido, "Analista finalizou validação clínica", "analista")
        print(f"{env.now:.1f}: Validação clínica de {pedido} finalizada! | ({tipo})")


        env.process(Desv4(env, pedido, tipo, monitor))

def Desv4(env, pedido, tipo,monitor):
    tipos = list(proporcao3.keys())
    pesos = list(proporcao3.values())
    resultado = random.choices(tipos, weights=pesos, k=1)[0]

    if resultado == "Critico":
        print(f"{env.now:.1f}: {pedido} classificado como {resultado} → segue para TELEFONEMA.")
        yield env.process(Telefonema(env,pedido,analista,tipo,monitor))
        return #Para evitar cair nos próximos ramos

    else:
        print(f"{env.now:.1f}: {pedido} classificado como {resultado} → segue para DISPONIBILIZACAO.")
        yield env.process(Disponibilizacao(env, pedido, tipo,monitor))
        return


def Disponibilizacao(env,pedido,tipo,monitor):
    monitor.log(env, pedido, "Disponibilização iniciada")
    print(f"{env.now:.1f}: Disponibilizando o {pedido} ({tipo})")

    # tempo de disponibilização (pode ser fixo ou aleatório e podemos mudar)
    yield env.timeout(tempo("disponibilizacao"))
    monitor.log(env, pedido, "Exame disponibilizado")
    monitor.fim(pedido, env.now)
    print(f"{env.now:.1f}: {pedido} ({tipo}) foi DISPONIBILIZADO no sistema e saiu do fluxo!")


def Telefonema(env,pedido,analista,tipo,monitor):
    monitor.log(env,pedido,"Inicio telefonema","analista")
    with analista.request() as req:
        # registra entrada na fila
        t_entrada_fila = env.now
        fila_atual = len(analista.queue)
        monitor.registrar_fila("analista", fila_atual, env.now)

        # aguarda disponibilidade do analista
        yield req  # aguarda até conseguir o recurso
        tempo_espera = env.now - t_entrada_fila
        monitor.registrar_tempo_espera("analista", tempo_espera)

        # início do serviço
        inicio_servico = env.now
        monitor.log(env,pedido,"Analista iniciou telefonema","analista")
        print(f"{env.now:.1f}: Telefonema do {pedido} iniciado")

        duracao_servico = tempo("telefonema")

        yield env.timeout(duracao_servico)

        fim_servico = env.now

        monitor.registrar_tempo_servico("analista", duracao_servico)
        monitor.registrar_uso_recurso("analista", inicio_servico, fim_servico)

        monitor.log(env,pedido,"Analista finalizou telefonema","analista")
        print(f"{env.now:.1f}: Telefonema do {pedido} finalizado")
        env.process(Disponibilizacao(env,pedido,tipo,monitor))



# ---------- MAIN ----------
monitor = Monitor()
env = simpy.Environment()
#proporção de urgentes e rotina (56,4% de urgencia e 43,6% de rotina)
proporcao = {"Urgente": 0.564, "Rotina": 0.436}
#proporção de adequação (1,16% de inadequados - média de janeiro a setembro)
proporcao2 = {"Adequado": 0.9884, "Inadequado":0.0116}
#porporção de criticidade (Da média mensal de exames, 1,38% tem resultados criticos e 98,62% resultados não críticos.)
proporcao3 = {"Critico": 0.0138, "Nao Critico": 0.9862}
# PriorityResource permite requests com prioridade
tec_lab = simpy.PriorityResource(env, capacity=6)  # 3 técnicos por plantão
tec_lab2 = simpy.PriorityResource(env, capacity=3)  # 3 técnicos por plantão
triagista = simpy.PriorityResource(env, capacity=2)  # 1 a cada plantão
analista = simpy.PriorityResource(env, capacity=1)  # 1 a cada plantão

#considerando 386 exames por dia e 92% que são coleta própria(própria do laboratório) e 8% externos(colhidos externamente)
env.process(criaChegadas(env, taxa=random.expovariate(0.181), tec_lab=tec_lab, proporcao=proporcao, p_coleta_externa=0.08,monitor=monitor))
env.run(until=320)



df_eventos = pd.DataFrame(monitor.registros)
df_eventos.sort_values(by=["pedido", "tempo"], inplace=True)

# tempo total de cada exame
df_tempos = pd.DataFrame([
    {"pedido": p, "tempo_total": monitor.tempo_total(p)}
    for p in monitor.tempos_totais
    if monitor.tempo_total(p) is not None
])

print("\n===== RELATÓRIO DE EVENTOS =====")
print(df_eventos.head(20))

# Filtra apenas exames que chegaram até a disponibilização
exames_finalizados = df_eventos.loc[df_eventos["evento"] == "Exame disponibilizado", "pedido"].unique()
df_tempos_finalizados = df_tempos[df_tempos["pedido"].isin(exames_finalizados)]

print("\n===== TEMPO TOTAL (SOMENTE EXAMES FINALIZADOS) =====")
print(df_tempos_finalizados.describe())

#print("\n===== TEMPO TOTAL POR EXAME =====")
#print(df_tempos.describe())

df_eventos.to_excel("eventos_simulacao.xlsx", index=False)
df_tempos.to_excel("tempos_totais.xlsx", index=False)


print("\n===== ESTATÍSTICAS DE RECURSOS =====")
tempo_total = env.now

for recurso, tempo_uso in monitor.tempo_uso_recurso.items():
    utilizacao = tempo_uso / tempo_total
    media_fila = (
        sum(q for _, q in monitor.fila_tam.get(recurso, [])) /
        len(monitor.fila_tam.get(recurso, []))
        if monitor.fila_tam.get(recurso) else 0
    )
    media_espera = (
        sum(monitor.tempo_espera.get(recurso, [])) / len(monitor.tempo_espera.get(recurso, []))
        if monitor.tempo_espera.get(recurso) else 0
    )
    media_servico = (
        sum(monitor.tempo_servico.get(recurso, [])) / len(monitor.tempo_servico.get(recurso, []))
        if monitor.tempo_servico.get(recurso) else 0
    )

    print(f"\nRecurso: {recurso}")
    print(f" Utilização: {utilizacao:.2%}")
    print(f" Tamanho médio da fila: {media_fila:.2f}")
    print(f" Tempo médio em fila: {media_espera:.2f} min")
    print(f" Tempo médio de atendimento: {media_servico:.2f} min")

"""No SimPy, o `simpy.Resource` padrão já implementa uma fila FIFO para as solicitações. Quando múltiplos processos solicitam o mesmo `Resource`, eles são enfileirados e atendidos na ordem em que fizeram a solicitação.

Se você precisa de prioridades, mas quer que as solicitações com a mesma prioridade sejam atendidas em FIFO, o `simpy.PriorityResource` também faz isso por padrão. A diferença que você observou antes pode ter sido devido a eventos ocorrendo no mesmo instante de simulação (`env.now`), e a ordem de processamento desses eventos pode não ser estritamente previsível sem um controle mais fino.

No seu código, você já está usando `simpy.PriorityResource`. Para garantir FIFO para a mesma prioridade, o SimPy já deveria estar fazendo isso. Se você quiser *apenas* FIFO sem prioridades, você pode mudar `simpy.PriorityResource` para `simpy.Resource`.

Por exemplo, para o recurso `tec_lab`, se você quisesse apenas FIFO (sem prioridade Urgente/Rotina para Coleta, Registro, Transporte e Classificação), você mudaria a linha:
"""

tec_lab = simpy.Resource(env, capacity=3)

def ColetaAmostra(env, pedido, tipo, tec_lab):
    # mapa numérico de prioridade (menor = atende antes)
    #prioridade = {"Urgente": 0, "Rotina": 1} # Remover esta linha
    #prio = prioridade.get(tipo, 1) # Remover esta linha

    # solicita o recurso com prioridade # Remover "priority=prio"
    with tec_lab.request() as req: # Alterar para tec_lab.request()
        yield req  # aguarda até conseguir o recurso
        #print(f"{env.now:.1f}: Coletando {pedido}. | ({tipo}, Prioridade = {prio})") # Remover ou ajustar print
        print(f"{env.now:.1f}: Coletando {pedido}. | ({tipo})") # Ajustar print

        # tempo de serviço por tipo (pode vir de um dicionário externo)
        t = tempo("coleta", tipo)
        yield env.timeout(t)

        print(f"{env.now:.1f}: {pedido} coletado! | ({tipo}) - durou {t} min")
        env.process(Registro_sistema(env,pedido,tec_lab,tipo))